-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 15:56:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rede_social_lavanderia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rede_social_lavanderia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rede_social_lavanderia` DEFAULT CHARACTER SET utf8 ;
USE `rede_social_lavanderia` ;

-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Usuario` (
  `id_Usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(255) NOT NULL,
  `Nome_completo` VARCHAR(50) NOT NULL,
  `E-mail` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(50) NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  `Foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Tema` (
  `id_Tema` BIGINT NOT NULL AUTO_INCREMENT,
  `Tipo_tema` VARCHAR(255) NOT NULL,
  `Tema` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rede_social_lavanderia`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rede_social_lavanderia`.`Postagem` (
  `id_Postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `Descricao_postagem` VARCHAR(2000) NOT NULL,
  `Data_hora` VARCHAR(255) NOT NULL,
  `Tema_id_Tema` BIGINT NULL,
  `Usuario_id_Usuario` BIGINT NULL,
  PRIMARY KEY (`id_Postagem`),
  INDEX `fk_Postagem_Usuario_idx` (`Usuario_id_Usuario` ASC) VISIBLE,
  INDEX `fk_Postagem_Tema1_idx` (`Tema_id_Tema` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Usuario`
    FOREIGN KEY (`Usuario_id_Usuario`)
    REFERENCES `rede_social_lavanderia`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagem_Tema1`
    FOREIGN KEY (`Tema_id_Tema`)
    REFERENCES `rede_social_lavanderia`.`Tema` (`id_Tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
